FROM mitmproxy/mitmproxy
WORKDIR /code
COPY main2.py main2.py
COPY run2.sh run2.sh
COPY har_dump.py har_dump.py
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
CMD ["/bin/sh", "run2.py"]
