version: "3"
services:
  web:
    image: tommyli123/webapp
    container_name: 'web'
    ports:
    - "5000:5000"
    networks:
    - mynetwork
  mitmdump:
    image: mitmproxy/mitmproxy
    container_name: 'mitmdump'
    command: mitmdump -w /home/mitmproxy/output3.log --mode regular
    ports:
    - 8080:8080
    volumes:
    - /home/tommy/mitm-volume:/home/mitmproxy
    networks:
    - mynetwork
  workflow:
    image: tommyli123/workflow1
    container_name: workflow
    command: python main.py
    depends_on:
    - mitmdump
    - web
    networks:
    - mynetwork
    environment:
      HTTP_PROXY: http://mitmdump:8080
      HTTPS_PROXY: http://mitmdump:8080

networks:
  mynetwork:
